import { RegistroTabla } from "./tableType";


export const datosEjemplo: RegistroTabla[] = [
    {
        id: '1',
        dni: '45678912X',
        numero: 'REG-001',
        responsable: 'Ana López',
        estado: 'agenda',
        fechaEntrega: '2025-05-20',
        tipoBase: 'tipo1',
    },
    {
        id: '2',
        dni: '78945612B',
        numero: 'REG-002',
        responsable: 'Carlos Martínez',
        estado: 'en proceso',
        fechaEntrega: '2025-05-18',
        tipoBase: 'tipo2',
    },
    {
        id: '3',
        dni: '12345678Z',
        numero: 'REG-003',
        responsable: 'Laura Gómez',
        estado: 'sin asignar',
        fechaEntrega: '2025-05-25',
        tipoBase: 'tipo1',
    },
    {
        id: '4',
        dni: '98765432A',
        numero: 'REG-004',
        responsable: 'Eduardo Sánchez',
        estado: 'agenda',
        fechaEntrega: '2025-05-22',
        tipoBase: 'tipo3',
    },
    {
        id: '5',
        dni: '56789012C',
        numero: 'REG-005',
        responsable: 'Carmen Rodríguez',
        estado: 'en proceso',
        fechaEntrega: '2025-05-19',
        tipoBase: 'tipo2',
    },
    {
        id: '6',
        dni: '34567890D',
        numero: 'REG-006',
        responsable: 'Manuel Fernández',
        estado: 'sin asignar',
        fechaEntrega: '2025-05-30',
        tipoBase: 'tipo3',
    },
    {
        id: '7',
        dni: '23456789E',
        numero: 'REG-007',
        responsable: 'Ana López',
        estado: 'agenda',
        fechaEntrega: '2025-05-21',
        tipoBase: 'tipo1',
    },
    {
        id: '8',
        dni: '87654321F',
        numero: 'REG-008',
        responsable: 'Carlos Martínez',
        estado: 'en proceso',
        fechaEntrega: '2025-06-05',
        tipoBase: 'tipo2',
    },
    {
        id: '9',
        dni: '65432198G',
        numero: 'REG-009',
        responsable: 'Laura Gómez',
        estado: 'sin asignar',
        fechaEntrega: '2025-06-10',
        tipoBase: 'tipo3',
    },
    {
        id: '10',
        dni: '54321678H',
        numero: 'REG-010',
        responsable: 'Eduardo Sánchez',
        estado: 'agenda',
        fechaEntrega: '2025-06-15',
        tipoBase: 'tipo1',
    },
];